<?php
/**
 * Created by PhpStorm.
 * User: saadia
 * Date: 23/01/2018
 * Time: 11:25
 */

namespace Drupal\hello_8\Plugin\Block;


use Drupal\Core\Access\AccessResult;
use Drupal\Core\Block\BlockBase;
use Drupal\Core\Session\AccountInterface;
class hello_8Block extends BlockBase
{

    /**
     * Builds and returns the renderable array for this block plugin.
     *
     * If a block should not be rendered because it has no content, then this
     * method must also ensure to return no content: it must then only return an
     * empty array, or an empty array with #cache set (with cacheability metadata
     * indicating the circumstances for it being empty).
     *
     * @return array
     *   A renderable array representing the content of the block.
     *
     * @see \Drupal\block\BlockViewBuilder
     */
    public function build()
    {
        return array(
      '#type' => 'markup',
      '#markup' => t('hello Drupal 8(block')
        );
        // TODO: Implement build() method.
    }

    /**
     * @param AccountInterface $account
     * @return \Drupal\Core\Access\AccessResult
     */
    protected function blockAccess(AccountInterface $account)
    {
        return AccessResult::allowedIfHasPermission($account, 'view hello messages'); // TODO: Change the autogenerated stub
    }
}